development: &default
  adapter: mysql2
  encoding: utf8
  database: swagger-rails_development
  host: localhost
  username: root
  password: "sssh9300662"

#test: &TEST
  #<<: *default
  #database: swagger-rails_test

