development: &default
  adapter: mysql2
  encoding: utf8
  database: op_api_portal
  host: 192.168.5.70
  username: root
  password: "oplink456"

#test: &TEST
  #<<: *default
  #database: swagger-rails_test

