development: &default
  adapter: mysql2
  encoding: utf8
  database: op_api_portal
  host: localhost
  username: root
  password: "1234"

#test: &TEST
  #<<: *default
  #database: swagger-rails_test

